name: Build on demo project

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12, 14, 16]
        demo_type: ['cra', 'next']

    steps:
      - uses: actions/checkout@v2
      - name: Init node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci && npm run build
      - run: cd sample/${{ matrix.demo_type }} && npm i && npm run build
