name: Check ESLint

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Init node env
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run fix:lint
        env:
          CI: true
